#!/usr/bin/env python3
"""Build the small shelf versions of the twenty card pictures.

    python3 tools/card-thumbs.py            (from the repo root)

Why this exists. The landing page shows all twenty cards at once, and un-zoomed a
card is drawn at most 201x290 real pixels -- measured across every screen from the
3in Jelly Star to a 2560 desktop, hover's 1.14 scale included. The card ART is up
to 756x1100, so the wall was sending about thirty times the picture any screen
could show, twenty times over: 5.99MB, ahead of the wall photograph itself.

So the wall gets these, and the full artwork is fetched only on a zoom -- which is
the only place it is ever drawn at its own size (on a Retina Mac a zoomed shelf
puts a card exactly 1:1 with its photograph). Same bargain bowl and fireflies
strike with their photographs, for the same reason.

BOX is 264x384: the 201x290 above, plus hover, plus margin. Don't cut it finer
without re-measuring the wall -- the whole point is that nothing on the shelf ever
looks softer than it did.

JPEG is safe here: every card is opaque (checked -- the four RGBA ones are alpha
255 throughout), and a photograph is what JPEG is for. Re-run after adding or
reshooting a card; it only rewrites what has changed.
"""
import glob, os, sys
from PIL import Image

BOX = (264, 384)
QUALITY = 84

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)

cards = sorted(set(glob.glob('*/*-card.png')) | set(glob.glob('*-card.png')))
if not cards:
    sys.exit('no *-card.png found -- run me from the repo root')

before = after = 0
for src in cards:
    dst = src[:-4] + '-sm.jpg'
    im = Image.open(src).convert('RGB')
    im.thumbnail(BOX, Image.LANCZOS)
    im.save(dst, 'JPEG', quality=QUALITY, optimize=True, progressive=True)
    before += os.path.getsize(src)
    after += os.path.getsize(dst)
    print('  %-34s %5dx%-4d  %6.0fKB -> %5.0fKB' % (
        dst, im.width, im.height,
        os.path.getsize(src) / 1024, os.path.getsize(dst) / 1024))

print('\n%d cards: %.2fMB -> %.0fKB  (%.0fx smaller)'
      % (len(cards), before / 1048576, after / 1024, before / after))

# The page caps how far a card may be enlarged at the card's own pixels, in three
# places. Reading that off the small version would cap a zoom far too low, so the
# TRUE size of each picture is written into index.html here rather than measured
# off the img at run time.
sizes = {}
for src in cards:
    slug = os.path.basename(src)[:-9]          # "<slug>-card.png"
    with Image.open(src) as im:
        sizes[slug] = im.size

block = 'var CARD_ART={' + ','.join(
    '%s:[%d,%d]' % (k, v[0], v[1]) for k, v in sorted(sizes.items())) + '};'

OPEN = '  /* card-art: generated by tools/card-thumbs.py -- do not hand-edit */\n'
SHUT = '  /* end card-art */'
page = open('index.html', encoding='utf-8').read()
a = page.index(OPEN) + len(OPEN)
b = page.index(SHUT)
new = page[:a] + '  ' + block + '\n' + page[b:]
if new != page:
    open('index.html', 'w', encoding='utf-8').write(new)
    print('index.html: card-art block rewritten (%d cards)' % len(sizes))
else:
    print('index.html: card-art block already current')
