#!/usr/bin/env python3
"""Put the wordless can't-reach-the-weather mark on the four live-data pieces.

Two small marks instead of a sentence: an exclamation inside a circle struck
through with a bar -- can't -- and beside it a turning circle, which says the
piece is going back for it on its own. Nothing to read, and the turning is the
honest part: the old wording claimed it was "still trying quietly" while showing
nothing that was trying.

Run from the repo root:  python3 tools/fetch-trouble.py
It rewrites the block between the markers on each of the four pieces, so it is
safe to run again. Don't hand-edit between the markers.
"""
import re, sys, os

A = '<!-- fetch-trouble: generated by tools/fetch-trouble.py -- do not hand-edit -->'
B = '<!-- /fetch-trouble -->'

BLOCK = A + """
<style>
  /* Shown when the weather cannot be reached. The struck-through exclamation is
     the trouble; the turning circle beside it is the piece going back for it by
     itself. Both take the page's own colour, so this reads the same on candle-lit
     wood as on a black plate. */
  /* Its own place, the same on all four: top centre, clear of the disc in either
     corner. Fixed, because these pieces are full-screen scenes and a mark in the
     normal flow of the document would land somewhere off the bottom of them. */
  #fetch-trouble{ position:fixed; top:20px; left:50%; transform:translateX(-50%);
    z-index:70; display:none; align-items:center; justify-content:center; gap:9px;
    color:currentColor; opacity:.62; pointer-events:none; }
  #fetch-trouble.visible{ display:flex; }
  #fetch-trouble svg{ display:block; width:19px; height:19px; overflow:visible; }
  #fetch-trouble .spin{ transform-origin:12px 12px; animation:ft-turn 1.5s linear infinite; }
  @keyframes ft-turn{ to{ transform:rotate(360deg); } }
  @media (prefers-reduced-motion: reduce){
    /* the turning is the message, so it is slowed rather than stopped */
    #fetch-trouble .spin{ animation-duration:4s; }
  }
</style>
<div id="fetch-trouble" role="img"
     aria-label="couldn't reach the weather -- showing the last real reading, trying again on its own">
  <!-- The bar runs the other way to the exclamation's own stroke. Struck the first
       way, the two lay almost along each other and the pair read as a clock face. -->
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round"
       aria-hidden="true">
    <circle cx="12" cy="12" r="9" stroke-width="1.4"/>
    <path d="M12 6.6v6.1" stroke-width="2.2"/>
    <circle cx="12" cy="16.6" r="1.15" fill="currentColor" stroke="none"/>
    <path d="M5.6 5.6 18.4 18.4" stroke-width="1.4"/>
  </svg>
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"
       stroke-linecap="round" aria-hidden="true">
    <g class="spin">
      <path d="M20 12a8 8 0 1 1-2.6-5.9"/>
      <path d="M20.4 3.6V7.4H16.6"/>
    </g>
  </svg>
</div>
""" + B


def patch(path, calls):
    s = open(path).read()
    before = s
    if A in s:
        s = re.sub(re.escape(A) + '.*?' + re.escape(B), lambda _: BLOCK, s, flags=re.S)
    else:
        s = s.replace('</body>', BLOCK + '\n</body>', 1)
        s = s.replace('</body>', """<script>
  // the two marks, shown and hidden where the sentence used to be
  function showFetchTrouble(){ var e=document.getElementById('fetch-trouble'); if(e) e.classList.add('visible'); }
  function hideFetchTrouble(){ var e=document.getElementById('fetch-trouble'); if(e) e.classList.remove('visible'); }
</script>
</body>""", 1)
    for old, new in calls:
        if old not in s:
            print('  !! not found in %s: %s' % (path, old[:60]))
            continue
        s = s.replace(old, new)
    if s != before:
        open(path, 'w').write(s)
        return True
    return False


SAY = 'showLocationNote("couldn\'t reach the weather just now — showing the last real reading, still trying quietly")'
JOBS = {
 'galileo/index.html': [
   ('if (weatherFetchFailures >= 2) ' + SAY, 'if (weatherFetchFailures >= 2) showFetchTrouble()'),
   ('if (weatherFetchFailures > 0){ weatherFetchFailures = 0; hideLocationNote(); }',
    'if (weatherFetchFailures > 0){ weatherFetchFailures = 0; hideFetchTrouble(); }')],
 'conometer/index.html': [
   ('if (humidityFetchFailures >= 2) showLocationNote("couldn\'t reach the humidity just now — showing the last real reading, still trying quietly")',
    'if (humidityFetchFailures >= 2) showFetchTrouble()'),
   ('if (humidityFetchFailures > 0){ humidityFetchFailures = 0; hideLocationNote(); }',
    'if (humidityFetchFailures > 0){ humidityFetchFailures = 0; hideFetchTrouble(); }')],
 'windower/index.html': [
   ('if (weatherFetchFailures >= 2) showLocationNote("couldn\'t reach the weather just now — showing the last real sky, still trying quietly")',
    'if (weatherFetchFailures >= 2) showFetchTrouble()'),
   ('if (weatherFetchFailures > 0){ weatherFetchFailures = 0; hideLocationNote(); }',
    'if (weatherFetchFailures > 0){ weatherFetchFailures = 0; hideFetchTrouble(); }')],
 'storm/index.html': [
   ('showWeatherNote("couldn\'t reach the weather just now — showing the last real reading, still trying quietly");',
    'showFetchTrouble();'),
   ('if(weatherFetchFailures > 0){ weatherFetchFailures = 0; hideWeatherNote(); }',
    'if(weatherFetchFailures > 0){ weatherFetchFailures = 0; hideFetchTrouble(); }')],
}

for f, calls in JOBS.items():
    print(('patched ' if patch(f, calls) else 'unchanged ') + f)
