#!/usr/bin/env python3
"""Put the shelf tags on every piece page.

The way ACROSS the site, as against the disc in the left corner which is the way
back. A mirrored disc in the right corner brings out the five brass plates, each
one cut from its own place on the case photograph; roll a plate and that group's
pieces come out beside it. Nothing on it is a word that isn't already engraved
into the furniture.

Run from the repo root after changing the shelves table in index.html:

    python3 tools/shelf-tags.py

It reads the groups out of index.html itself -- that table is the one source of
truth for what is on which shelf -- and rewrites the block between the two
shelf-tags markers on each piece page. Everything outside the markers is left
alone, so it is safe to run again at any time. Hand-editing the block is not:
the next run overwrites it.
"""
import re, glob, sys, os

MARK_A = '<!-- shelf-tags: generated by tools/shelf-tags.py -- do not hand-edit -->'
MARK_B = '<!-- /shelf-tags -->'

# where each plate sits in shelves.jpg, and the plate's own width there
PLATE_Y = {'instrumenta':304, 'tactilia':488, 'systema':677, 'natura':866, 'phenomena':1054}
PLATE_X, PLATE_W, PHOTO_W = 419, 157, 990
TAG_W = 132                      # how wide the plate is drawn on a piece page

# pages that already keep something in the top right corner, and how far down it
# has to move to leave the disc its own space
NUDGE = {'roller': '#hint{ top:74px; }'}


def groups(root):
    """The five groups and their pieces, straight out of the case's own table."""
    s = open(os.path.join(root, 'index.html')).read()
    block = re.search(r'shelves:\[(.*?)\n    \]\n  \};', s, re.S).group(1)
    out = []
    for m in re.finditer(r"name:'(\w+)'.*?pieces:\[(.*?)\]\s*\}", m_block := block, re.S):
        out.append((m.group(1),
                    re.findall(r"\['([\w-]+)','([^']+)','([^']+)'\]", m.group(2))))
    if len(out) != 5:
        sys.exit('expected five shelves, read %d -- has the table changed shape?' % len(out))
    return out


def block(slug, groups_, extra=''):
    scale = TAG_W / PLATE_W
    bg = 'url(../shelves.jpg) %dpx %dpx / %dpx auto'
    rows = []
    for name, pieces in groups_:
        pos = bg % (-PLATE_X * scale, -PLATE_Y[name] * scale, PHOTO_W * scale)
        cards = ''.join(
            '<a%s href="../%s/"><img src="../%s" alt="%s"></a>'
            % (' class="here"' if p == slug else '', p, card, p)
            for p, href, card in pieces)
        rows.append(
            '  <div class="row"%s>\n'
            '    <span class="pieces">%s</span>\n'
            '    <a class="tag" href="../index.html#%s" style="background:%s">%s</a>\n'
            '  </div>' % (' data-here="1"' if any(p == slug for p, _, _ in pieces) else '',
                          cards, name, pos, name))

    return '\n'.join([MARK_A, """<style>
  /* The disc in the right corner is the mirror of the one in the left: same brass
     off the same plinth, arrow the other way. Touched, the five plates come out --
     the very plates off the case, each cut from its own place in the photograph.
     Roll one and that group's pieces come out beside it. */
  #shelfdisc{ position:fixed; top:18px; right:22px; z-index:61;
    width:38px; height:38px; display:grid; place-items:center;
    appearance:none; border:0; background:none; padding:0; cursor:pointer;
    opacity:.55; transition:opacity .3s ease;
    filter:drop-shadow(0 1px 3px rgba(0,0,0,.65)); }
  #shelfdisc:hover, #shelfdisc[aria-expanded="true"]{ opacity:.95; }
  #shelfdisc img{ grid-area:1/1; width:100%; height:100%; display:block; }
  #shelfdisc i{ grid-area:1/1; font-style:normal; font-weight:700;
    font-size:19px; line-height:1; font-family:Georgia, serif; color:#33230a;
    text-shadow:0 1px 0 rgba(255,238,196,.5), 0 -1px 1px rgba(0,0,0,.35); }
  #shelfdisc:focus-visible{ outline:1px solid rgba(242,233,216,.45); outline-offset:4px; }

  #plates{ position:fixed; top:68px; right:22px; z-index:60;
    display:flex; flex-direction:column; align-items:flex-end; gap:10px;
    opacity:0; transform:translateX(14px); pointer-events:none;
    transition:opacity .35s ease, transform .35s cubic-bezier(.22,.66,.24,1); }
  #plates.open{ opacity:1; transform:none; pointer-events:auto; }
  #plates .row{ display:flex; align-items:center; justify-content:flex-end; gap:8px; }
  #plates .tag{ display:flex; align-items:center; justify-content:center; flex:none;
    width:132px; height:20px; cursor:pointer; text-decoration:none;
    font:700 11px/1 'Cormorant Garamond', Georgia, serif; letter-spacing:.02em;
    color:#3b2807; text-shadow:0 1px 0 rgba(255,238,196,.42), 0 -1px 1px rgba(0,0,0,.3);
    filter:drop-shadow(0 2px 4px rgba(0,0,0,.6));
    opacity:.9; transition:opacity .25s ease, transform .25s ease; }
  #plates .row:hover .tag, #plates .row:focus-within .tag,
  #plates .row.rolled .tag{ opacity:1; transform:translateX(-2px); }
  /* a group's pieces stay folded away until its plate is rolled or tapped */
  #plates .pieces{ display:flex; gap:6px; overflow:hidden; max-width:0;
    transition:max-width .4s cubic-bezier(.22,.66,.24,1); }
  #plates .row:hover .pieces, #plates .row:focus-within .pieces,
  #plates .row.rolled .pieces{ max-width:360px; }
  #plates .pieces a{ display:block; width:40px; height:53px; flex:none; border-radius:2px;
    overflow:hidden; box-shadow:0 2px 4px rgba(0,0,0,.8), 0 0 0 1px rgba(0,0,0,.5);
    opacity:.9; transition:opacity .2s ease, transform .2s ease; }
  #plates .pieces a:hover{ opacity:1; transform:scale(1.08); }
  #plates .pieces a.here{ opacity:1; box-shadow:0 2px 4px rgba(0,0,0,.8), 0 0 0 2px #bda869; }
  #plates img{ width:100%; height:100%; object-fit:cover; display:block; }
  @media (prefers-reduced-motion: reduce){
    #plates, #plates .pieces{ transition:none; }
  }
""" + ('  ' + extra + '\n' if extra else '') + """</style>
<button type="button" id="shelfdisc" aria-expanded="false" aria-controls="plates"
        aria-label="the other shelves"><img src="../shelfdisk.png" alt=""><i>&#8594;</i></button>
<div id="plates">
""" + '\n'.join(rows) + """
</div>
<script>
(function(){
  var disc=document.getElementById('shelfdisc'), box=document.getElementById('plates');
  var rows=[].slice.call(box.querySelectorAll('.row'));
  function unroll(){ rows.forEach(function(r){ r.classList.remove('rolled'); }); }
  function shut(){ box.classList.remove('open'); disc.setAttribute('aria-expanded','false'); unroll(); }

  disc.addEventListener('click', function(ev){
    ev.stopPropagation();
    var open=box.classList.toggle('open');
    disc.setAttribute('aria-expanded', open?'true':'false');
    if(!open) unroll();
  });

  // Same bargain the case itself strikes: a mouse can hover, so a plate is a link
  // straight to its shelf. A thumb cannot, so the first tap on a plate rolls its
  // pieces out and only the second one goes to the shelf.
  var FINE=matchMedia('(hover: hover) and (pointer: fine)');
  rows.forEach(function(row){
    row.querySelector('.tag').addEventListener('click', function(ev){
      if(FINE.matches) return;
      if(row.classList.contains('rolled')) return;
      ev.preventDefault();
      unroll(); row.classList.add('rolled');
    });
  });

  document.addEventListener('click', function(ev){
    if(!box.contains(ev.target) && ev.target!==disc) shut();
  });
  document.addEventListener('keydown', function(e){ if(e.key==='Escape') shut(); });
})();
</script>""", MARK_B])


def main():
    root = os.getcwd()
    gs = groups(root)
    known = {p for _, pieces in gs for p, _, _ in pieces}
    touched = []
    for f in sorted(glob.glob('*/index.html')):
        slug = os.path.dirname(f)
        if slug not in known:
            continue
        s = open(f).read()
        new = block(slug, gs, NUDGE.get(slug, ''))
        if MARK_A in s:
            s = re.sub(re.escape(MARK_A) + '.*?' + re.escape(MARK_B), lambda _: new, s, flags=re.S)
        else:
            s = s.replace('</body>', new + '\n</body>', 1)
        open(f, 'w').write(s)
        touched.append(slug)
    print('shelf tags written to %d pieces: %s' % (len(touched), ', '.join(touched)))
    missing = known - set(touched)
    if missing:
        print('NOT written (no page found):', ', '.join(sorted(missing)))


if __name__ == '__main__':
    main()
