#!/usr/bin/env python3
"""Make a click on a slider's track move it, in every browser.

    python3 tools/slider-click.py          (from the repo root)

Why. A native <input type=range> jumps to the clicked position in Chrome and
Firefox, but NOT in Safari on macOS, where the thumb only responds to a drag.
Her report, twice: "clicking on a slider doesn't seem to change it, only dragging
it" and "i still can't get all the sliders to move when i click them instead of
pulling". Nothing on this site was blocking it -- measured, fireflies' sliders
jump correctly under Chromium -- so it is the browser, and the fix is to stop
depending on the browser.

One capture-phase pointerdown listener per page sets the value from where the
pointer landed and fires input and change, so the piece's own handlers pick it up
unchanged. Where the browser already jumps it computes the same value, so it is
harmless there; and the native drag still works afterwards either way.

Don't hand-edit between the slider-click markers -- re-run this instead.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
START, END = '<!-- slider-click -->', '<!-- /slider-click -->'

BLOCK = START + """
<script>
/* GENERATED by tools/slider-click.py -- do not hand-edit between the markers.
   A click on a slider's track moves it, in every browser. Safari on macOS does
   not do this natively; Chrome and Firefox do, and there it computes the same
   value, so nothing changes. Capture phase, so a piece that stops propagation on
   its own sliders still gets it. */
addEventListener('pointerdown', function(e){
  var el = e.target;
  if(!el || el.tagName !== 'INPUT' || el.type !== 'range' || el.disabled) return;
  var r = el.getBoundingClientRect();
  if(!r.width) return;
  var min = parseFloat(el.min); if(isNaN(min)) min = 0;
  var max = parseFloat(el.max); if(isNaN(max)) max = 100;
  var step = parseFloat(el.step); if(!(step > 0)) step = 1;
  var frac = (e.clientX - r.left) / r.width;
  frac = frac < 0 ? 0 : frac > 1 ? 1 : frac;
  var v = min + frac * (max - min);
  v = Math.round((v - min) / step) * step + min;
  v = v < min ? min : v > max ? max : v;
  if (String(v) === String(el.value)) return;
  el.value = v;
  el.dispatchEvent(new Event('input',  { bubbles: true }));
  el.dispatchEvent(new Event('change', { bubbles: true }));
}, true);
</script>
""" + END

pages = sorted(set(glob.glob('*.html')) | set(glob.glob('*/index.html')))
esc = lambda t: re.escape(t)
rx = re.compile(esc(START) + r'[\s\S]*?' + esc(END))
done = 0
for p in pages:
    src = open(p, encoding='utf-8').read()
    if 'type="range"' not in src and "type='range'" not in src:
        continue
    new = rx.sub(BLOCK, src) if rx.search(src) else src.replace('</body>', BLOCK + '\n</body>')
    if new != src:
        open(p, 'w', encoding='utf-8').write(new)
        print('  ', p)
        done += 1
print('\n%d pages with sliders updated' % done)
