const { chromium } = require('playwright-core');
const fs = require('fs');
const ROOT = '/home/user/legendary-souffle-5af442';
const SLUGS = ['candler','roller','lamp','rain','ant','conometer','gyre','birds','bowl','chimes',
               'chladni','fireflies','kaleidoscope','moths','musebox','pendulum'];
const CAP = 15, ALREADY_BIG = 40;
const START = '<!-- touch-targets -->', END = '<!-- /touch-targets -->';

(async () => {
  const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-sandbox'] });
  for (const slug of SLUGS) {
    const c = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
    const p = await c.newPage();
    await p.goto('http://localhost:8137/'+slug+'/', { waitUntil:'domcontentloaded' });
    await p.waitForTimeout(1800);
    const specs = await p.evaluate(({CAP, ALREADY_BIG}) => {
      // THIS TOOL IS NOT IDEMPOTENT UNLESS THIS RUNS FIRST, and getting it wrong
      // is silent and destructive. The block written by the LAST run is in the
      // page, and its negative margins are part of the computed style -- measure
      // on top of them and they compound: padding stays 15px but margin-top goes
      // -28 to -43 on a second run, -58 on a third, dragging every slider up the
      // page. It also inflates the measured HEIGHT, so a slider already grown
      // past ALREADY_BIG gets skipped and freezes at whatever it happened to be.
      // Taking the old block out first means a run always starts from the page's
      // own layout, and running twice gives the same answer as running once.
      for (const st of document.querySelectorAll('style'))
        if (/GENERATED by tools\/touch-targets/.test(st.textContent)) st.remove();
      const inter = [...document.querySelectorAll('button,input,select,a,[role="button"],.piece,.swatch,.mbtn,label')]
        .map(e=>({e, r:e.getBoundingClientRect()})).filter(o=>o.r.width>2 && o.r.height>1);
      const out = [];
      for (const s of inter.filter(o=>o.e.tagName==='INPUT' && o.e.type==='range')) {
        if (!s.e.id) continue;
        if (s.r.height >= ALREADY_BIG) continue;      // already takes a thumb
        let up = Infinity, down = Infinity;
        for (const o of inter) {
          if (o.e === s.e || o.e.contains(s.e) || s.e.contains(o.e)) continue;
          if (o.r.right < s.r.left+2 || o.r.left > s.r.right-2) continue;
          if (o.r.bottom <= s.r.top) up = Math.min(up, s.r.top - o.r.bottom);
          else if (o.r.top >= s.r.bottom) down = Math.min(down, o.r.top - s.r.bottom);
        }
        const cs = getComputedStyle(s.e);
        const pad = g => Math.max(0, Math.min(CAP, Math.floor((g===Infinity ? CAP*2 : g) / 2)));
        // CSS scales every radius down proportionally when they don't fit the box,
        // so a declared 4px on a 4px-tall track is really 2px on screen. The
        // declared figure is what getComputedStyle hands back, so clamp it here
        // or the cap comes out a different shape from the one it replaced.
        const lim = Math.min(s.r.height/2, s.r.width/2);
        const rad = k => Math.round(Math.min(parseFloat(cs[k])||0, lim)*100)/100;
        out.push({ id: s.e.id, h: Math.round(s.r.height),
                   pt: pad(up), pb: pad(down),
                   mt: parseFloat(cs.marginTop)||0, mb: parseFloat(cs.marginBottom)||0,
                   rtl: rad('borderTopLeftRadius'), rtr: rad('borderTopRightRadius'),
                   rbr: rad('borderBottomRightRadius'), rbl: rad('borderBottomLeftRadius') });
      }
      return out;
    }, {CAP, ALREADY_BIG});
    await c.close();
    if (!specs.length) { console.log(slug.padEnd(13)+'no sliders to grow'); continue; }

    const lines = specs.filter(s=>s.pt||s.pb).map(s => {
      // border-radius is measured off the OUTER box, so padding eats the rounding
      // off the painted strip and leaves it with square ends. An elliptical radius
      // gives the vertical axis back exactly what the padding took, so the line
      // keeps the caps it always had.
      const anyR = s.rtl || s.rtr || s.rbr || s.rbl;
      const radius = anyR
        ? ` border-radius:${s.rtl}px ${s.rtr}px ${s.rbr}px ${s.rbl}px / ` +
          `${s.rtl + s.pt}px ${s.rtr + s.pt}px ${s.rbr + s.pb}px ${s.rbl + s.pb}px;`
        : '';
      return `  input[type=range]#${s.id}{ box-sizing:content-box; background-origin:content-box; background-clip:content-box;` +
             `${radius} padding:${s.pt}px 0 ${s.pb}px; ` +
             `margin-top:${s.mt - s.pt}px; margin-bottom:${s.mb - s.pb}px; }`;
    });
    if (!lines.length) { console.log(slug.padEnd(13)+'nothing to do'); continue; }

    const block = `${START}
<style>
  /* GENERATED by tools/touch-targets.js -- do not hand-edit between the markers.
     A 3px-tall slider is a mouse dimension: a mouse is pixel-precise, a thumb is
     about 9mm across and covers the whole track the moment it lands on it. These
     rules grow the BODY that catches a thumb without moving the painted line by a
     pixel -- the padding grows the box, background-clip keeps the paint in the
     content strip, and the matching negative margin gives back the space so
     nothing on the page shifts. Each slider grows only as far as half the gap to
     its nearest neighbour, so no two ever overlap and steal each other's taps. */
  @media (pointer: coarse){
${lines.join('\n')}
  }
</style>
${END}`;

    const file = `${ROOT}/${slug}/index.html`;
    let src = fs.readFileSync(file, 'utf8');
    const re = new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g,'\\$&') + '[\\s\\S]*?' + END.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
    if (re.test(src)) src = src.replace(re, block);
    else src = src.replace('</body>', block + '\n</body>');
    fs.writeFileSync(file, src);
    console.log(slug.padEnd(13) + specs.map(s=>`${s.id} ${s.h}->${s.h+s.pt+s.pb}`).join('  '));
  }
  await b.close();
})();
